/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsNewRouteImport } from './routes/trips.new'
import { Route as ShareTripIdRouteImport } from './routes/share.$tripId'
import { Route as TripsTripIdIndexRouteImport } from './routes/trips.$tripId.index'
import { Route as TripsTripIdViewRouteImport } from './routes/trips.$tripId.view'
import { Route as TripsTripIdItineraryRouteImport } from './routes/trips.$tripId.itinerary'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsNewRoute = TripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTripIdRoute = ShareTripIdRouteImport.update({
  id: '/share/$tripId',
  path: '/share/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdIndexRoute = TripsTripIdIndexRouteImport.update({
  id: '/trips/$tripId/',
  path: '/trips/$tripId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdViewRoute = TripsTripIdViewRouteImport.update({
  id: '/trips/$tripId/view',
  path: '/trips/$tripId/view',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdItineraryRoute = TripsTripIdItineraryRouteImport.update({
  id: '/trips/$tripId/itinerary',
  path: '/trips/$tripId/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/budget': typeof BudgetRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot': typeof ForgotRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/packing': typeof PackingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/share/$tripId': typeof ShareTripIdRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/': typeof TripsIndexRoute
  '/trips/$tripId/itinerary': typeof TripsTripIdItineraryRoute
  '/trips/$tripId/view': typeof TripsTripIdViewRoute
  '/trips/$tripId/': typeof TripsTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/budget': typeof BudgetRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot': typeof ForgotRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/packing': typeof PackingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/share/$tripId': typeof ShareTripIdRoute
  '/trips/new': typeof TripsNewRoute
  '/trips': typeof TripsIndexRoute
  '/trips/$tripId/itinerary': typeof TripsTripIdItineraryRoute
  '/trips/$tripId/view': typeof TripsTripIdViewRoute
  '/trips/$tripId': typeof TripsTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/budget': typeof BudgetRoute
  '/cities': typeof CitiesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot': typeof ForgotRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/packing': typeof PackingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/share/$tripId': typeof ShareTripIdRoute
  '/trips/new': typeof TripsNewRoute
  '/trips/': typeof TripsIndexRoute
  '/trips/$tripId/itinerary': typeof TripsTripIdItineraryRoute
  '/trips/$tripId/view': typeof TripsTripIdViewRoute
  '/trips/$tripId/': typeof TripsTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/budget'
    | '/cities'
    | '/dashboard'
    | '/forgot'
    | '/journal'
    | '/login'
    | '/packing'
    | '/settings'
    | '/signup'
    | '/share/$tripId'
    | '/trips/new'
    | '/trips/'
    | '/trips/$tripId/itinerary'
    | '/trips/$tripId/view'
    | '/trips/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/admin'
    | '/budget'
    | '/cities'
    | '/dashboard'
    | '/forgot'
    | '/journal'
    | '/login'
    | '/packing'
    | '/settings'
    | '/signup'
    | '/share/$tripId'
    | '/trips/new'
    | '/trips'
    | '/trips/$tripId/itinerary'
    | '/trips/$tripId/view'
    | '/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/budget'
    | '/cities'
    | '/dashboard'
    | '/forgot'
    | '/journal'
    | '/login'
    | '/packing'
    | '/settings'
    | '/signup'
    | '/share/$tripId'
    | '/trips/new'
    | '/trips/'
    | '/trips/$tripId/itinerary'
    | '/trips/$tripId/view'
    | '/trips/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRoute
  BudgetRoute: typeof BudgetRoute
  CitiesRoute: typeof CitiesRoute
  DashboardRoute: typeof DashboardRoute
  ForgotRoute: typeof ForgotRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  PackingRoute: typeof PackingRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ShareTripIdRoute: typeof ShareTripIdRoute
  TripsNewRoute: typeof TripsNewRoute
  TripsIndexRoute: typeof TripsIndexRoute
  TripsTripIdItineraryRoute: typeof TripsTripIdItineraryRoute
  TripsTripIdViewRoute: typeof TripsTripIdViewRoute
  TripsTripIdIndexRoute: typeof TripsTripIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/new': {
      id: '/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof TripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$tripId': {
      id: '/share/$tripId'
      path: '/share/$tripId'
      fullPath: '/share/$tripId'
      preLoaderRoute: typeof ShareTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/': {
      id: '/trips/$tripId/'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId/'
      preLoaderRoute: typeof TripsTripIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/view': {
      id: '/trips/$tripId/view'
      path: '/trips/$tripId/view'
      fullPath: '/trips/$tripId/view'
      preLoaderRoute: typeof TripsTripIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/itinerary': {
      id: '/trips/$tripId/itinerary'
      path: '/trips/$tripId/itinerary'
      fullPath: '/trips/$tripId/itinerary'
      preLoaderRoute: typeof TripsTripIdItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRoute,
  BudgetRoute: BudgetRoute,
  CitiesRoute: CitiesRoute,
  DashboardRoute: DashboardRoute,
  ForgotRoute: ForgotRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  PackingRoute: PackingRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ShareTripIdRoute: ShareTripIdRoute,
  TripsNewRoute: TripsNewRoute,
  TripsIndexRoute: TripsIndexRoute,
  TripsTripIdItineraryRoute: TripsTripIdItineraryRoute,
  TripsTripIdViewRoute: TripsTripIdViewRoute,
  TripsTripIdIndexRoute: TripsTripIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
